/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: kitt3n.d (https://sketchfab.com/kitten.d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/754b84bda1ec4f47b2aa53a89c4f2309
title: Mug
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/mug2/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Mug_MugMaterial_0.geometry}
            material={materials.MugMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/mug2/scene.gltf");
