/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: French Baguette (https://sketchfab.com/FrenchBaguette)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/5f5ccee1514c440887c072fae8e0d699
title: Coffee Mug (School Project)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/mug/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null} position={[-8, -26, 8]}>
      <group rotation={[Math.PI, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.Mug1_Mug_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Mug1_Coffee_0.geometry}
            material={materials.Coffee}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/mug/scene.gltf");
