/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: kitt3n.d (https://sketchfab.com/kitten.d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/754b84bda1ec4f47b2aa53a89c4f2309
title: Mug
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

import img from "../../img/cat.png"

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/mug2/scene.gltf");
  const texture = useTexture(img)

  return (
    <mesh
      geometry={nodes.Mug_MugMaterial_0.geometry}
      args={[1, 1, 1]}
    >
      <meshStandardMaterial attach="material" map={texture} />
    </mesh>
  );
}

useGLTF.preload("/models/mug2/scene.gltf");
